### ISSUE TITLE
Booking request form: Filters and selection options

### ISSUE THREAD

**Issue by sberger** [melanietreitinger/mod_bookit#2]
Aktuell kann im Buchungsformular aus einer Kategorie "Semester" und "Raum" ausgewählt werden.

Ebenso soll man aus weiteren voreinstellbaren Kategorien auswählen können:

* Fakultät / Einrichtung*
* Zeitslot*

Die Voreinstellungen für diese Kategorien sollen administrativ konfigurierbar sein:

- Semester
- Raum
- Fakultät / Einrichtung
- Zeitslots

**Comment by melanietreitinger** [comment]
See #44
