### ISSUE TITLE
Add overview of booked events for booking person

### ISSUE THREAD

**Issue by pdorok** [melanietreitinger/mod_bookit#21]
- The overview should be a list of all events, which were requested by the booking person. 
- The overview has short information about the event: ID, Titel, room. status, Link-Button "Checklist"). 
- All columns are filterable 
- When the booking person clicks on the title of one event in the overview, then the detail view of the event opens. (The detail view shows all information from the booking request form; read only)

**Comment by sberger** [comment]
Is part of #20 and #22

**Comment by sberger** [comment]
look for #20
