### ISSUE TITLE
Calendar: Add overview of booked events for service team *must have*

### ISSUE THREAD

**Issue by LeleNe** [melanietreitinger/mod_bookit#22]
- The overview should be a list of all events
- The overview has short information about the event: ID, Titel, room. status, Link-Button "Checklist", time stemp of last change, last change by... ). 
- All columns are filterable 
- When the service team clicks on the title of one event in the overview, then the detail view of the event opens. (the detail view shows all information from the booking request form, read and write)
- the detail view has the options SAVE and DISMISS UNSAVED CHANGES at the end of the form

**Comment by sberger** [comment]
Is part of #20 and #21

**Comment by sberger** [comment]
look for #20
