### ISSUE TITLE
Calendar: Add function to edit booking requests *must have*

### ISSUE THREAD

**Issue by FelixSchmandt** [melanietreitinger/mod_bookit#33]
- As service staff I want to be able to edit booking requests
- After booking parties have sent a request
- So that missing information can be added or mistakes corrected

**Comment by melanietreitinger** [comment]
See also #1

**Comment by melanietreitinger** [comment]
Es wird zwischen folgenden Akteuren unterschieden:
| function | database column |
|----------|-----------------|
| Buchende Person | usermodified (current userid) |
| Prüfungsverantwortliche Person | personinchargeid |
| Weitere Prüfende | otherexaminers |

Umsetzung:
-> User-Suchfelder, keine Freitextfelder (alle beteiligten Personen müssen einen Moodle Account haben)
-> berechtigt für Detailansicht 

Nachteilsausgleich bleibt in Formular:
- Checkbox: Zeitverlängerung
- Texteingabefeld: Sonstiger NTA

> [!NOTE]
> | Action | db fields |
> |----------|-----------------|
> | Remove from db | personinchargename, personinchargeemail | 
> | New in db | otherexaminers (->fk), timecompensation | 
> | Rename | status in bookingstatus |

**Comment by melanietreitinger** [comment]
Continue working on #1
