### ISSUE TITLE
:bug: Installation error

### ISSUE THREAD

**Issue by robertodamm** [melanietreitinger/mod_bookit#53]
**Describe the bug**
When installing mod_bookit this error is displayed:

Fehler: Class "mod_bookit\local\entity\category" not found

[Weitere Informationen über diesen Fehler](https://docs.moodle.org/405/de/error/moodle/generalexceptionmessage)

Debug-Info: 
Error code: generalexceptionmessage×Diese Systemnachricht ablehnen
Stack trace: 
line 34 of /mod/bookit/db/install.php: Error thrown
line 891 of /lib/upgradelib.php: call to xmldb_bookit_install()
line 651 of /lib/upgradelib.php: call to upgrade_plugins_modules()
line 1937 of /lib/upgradelib.php: call to upgrade_plugins()
line 719 of /admin/index.php: call to upgrade_noncore()

**To Reproduce**
1. Copy code to Moodle
2. Start installer

**Expected behavior**
This should not happen

**Additional context**
Modify to fix:
/mod/bookit/db/install.php

Line 25:
use mod_bookit\local\entity\bookit_category;

Line 34:
    $category = new bookit_category('Rooms', 'Examrooms');

Line 44:
        $resource = new \mod_bookit\local\entity\bookit_resource('Exam room ' . $i, 'Capacity 255 seats', 1, $category->id);

Line 61:
        $event = new \mod_bookit\local\entity\bookit_event(

**Comment by sberger** [comment]
Is already corrected in the feature branch
