### ISSUE TITLE
:bug: Event details that have already been entered are lost when the event is called up again

### ISSUE THREAD

**Issue by sberger** [melanietreitinger/mod_bookit#54]
**Describe the bug**
I have created an new event (as a trainer in the course). When I call up the event form again, all the entries below the ‘Person in charge’ field have been lost. 

**To Reproduce**
1. Create a new event entry and save it. Fill in all possible fields of the event.
2. Open the event again by clicking on the event entry.
3. See error

**Expected behavior**
Either they are not entered in the database after the event has been created, or they are not shown again.

**Screenshots**
![Termindetails verschwinden beim Wiederaufruf](https://github.com/user-attachments/assets/603744ef-f5f7-4519-8422-04ed79fe40d5)

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma
 - Browser Chrome
 - VersionVersion 130.0.6723.92 (Offizieller Build) (arm64)
 - 
**Smartphone (please complete the following information):**

**Additional context**
...

**Comment by melanietreitinger** [comment]
Will be fixed with #1

**Comment by sberger** [comment]
Inputs are now retained.
