### ISSUE TITLE
Language strings for "calendar" --> today, month, week, day | resources, list, timeline

### ISSUE THREAD

**Issue by sberger** [melanietreitinger/mod_bookit#57]
Where are the language strings defined?

![Language calenderviews Screenshot](https://github.com/user-attachments/assets/411c029b-224a-4494-b577-8e1cbf9c503a)

**Comment by melanietreitinger** [comment]
File: amd/src/calendar.js
-> look for "headerToolbar"

Translation of the button texts using Moodle strings:

```
const str_request_booking = await getString('addbooking', 'mod_bookit');
const str_today = await getString('today');
const str_month = await getString('month');
const str_week = await getString('week');
const str_day = await getString('day', 'calendar');
const str_list = await getString('upcomingevents', 'calendar');
```

Docs: https://github.com/vkurko/calendar?tab=readme-ov-file#headertoolbar
Example: https://github.com/vkurko/calendar/issues/311

**Comment by sberger** [comment]
Language customisation can be done via the strings as set above.
