### ISSUE TITLE
:bug: ...Calendar:Request New Event does not work because you can´t choose a person in charge + examiner

### ISSUE THREAD

**Issue by DeniseMaterna** [melanietreitinger/mod_bookit#61]
Sorry, but you do not currently have permissions to do that (Review course enrolments).
File: /lib/accesslib.php
Line: 875
Error code: nopermissions
* line 875 of /lib/accesslib.php: core\exception\required_capability_exception thrown
* line 559 of /enrol/externallib.php: call to require_capability()
* line ? of unknownfile: call to core_enrol_external::get_potential_users()
* line 253 of /lib/external/classes/external_api.php: call to call_user_func_array()
* line 83 of /lib/ajax/service.php: call to core_external\external_api::call_external_function()

Error code: nopermissions
* line 875 of /lib/accesslib.php: core\exception\required_capability_exception thrown
* line 559 of /enrol/externallib.php: call to require_capability()
* line ? of unknownfile: call to core_enrol_external::get_potential_users()
* line 253 of /lib/external/classes/external_api.php: call to call_user_func_array()
* line 83 of /lib/ajax/service.php: call to core_external\external_api::call_external_function()

**Comment by sberger** [comment]
to discuss: This means that the ‘examiner’ role must be automatically entered as an examiner when a booking is created?

**Comment by sberger** [comment]
look at issue #1
