### ISSUE TITLE
Disable drag-and-drop functionality for calendar events for all roles.

### ISSUE THREAD

**Issue by pdorok** [melanietreitinger/mod_bookit#7]

**Comment by melanietreitinger** [comment]
Fixed!

https://github.com/vkurko/calendar?tab=readme-ov-file#eventstarteditable
`eventStartEditable: false`

**Comment by sberger** [comment]
in any roles: An event can still be touched at the bottom and moved at the bottom. This has no effect on the time entered, but is annoying as the event appears longer than it is. After reopening the page, the event will be displayed in the entered length again.
